const DATABASE_NAME = 'jobzdb';
const DATABASE_USERNAME = 'root';
const DATABASE_PASSWORD = 'm8463854';
const DATABASE_HOST = 'localhost';
const DATABASE_PORT = 3306;

export {
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_HOST,
  DATABASE_PORT,
};
